import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, padding: 8 },
  header: { alignItems: "center", gap: 4, paddingBottom: 6 },
  title: { fontSize: 24, fontWeight: "800" },
  subtitle: { fontSize: 13, opacity: 0.9 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  error: { fontSize: 14, textAlign: "center" },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  meta: { fontSize: 13, opacity: 0.9 },
  solvedWrap: { gap: 8, paddingVertical: 6 },
  solvedGroup: {
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  solvedTitle: { fontSize: 13, fontWeight: "800" },
  solvedWords: { fontSize: 12, fontWeight: "600", marginTop: 3 },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    paddingVertical: 4,
    justifyContent: "center",
    width: "50%",
    alignSelf: "center",
  },
  tile: {
    minWidth: 0,
    aspectRatio: 2,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  tileText: { fontSize: 10, fontWeight: "800", textAlign: "center" },
  message: { textAlign: "center", paddingVertical: 4, fontSize: 13 },
  win: {
    textAlign: "center",
    paddingVertical: 4,
    fontSize: 15,
    fontWeight: "800",
  },
  controls: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    paddingTop: 4,
  },
  controlBtn: { borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
  controlText: { fontWeight: "800" },
  mistakesRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    paddingTop: 6,
    paddingBottom: 6,
    alignItems: "center",
  },
  mistakeDot: { width: 14, height: 14, borderRadius: 14, borderWidth: 1 },
});
